initial.o ObjDepends/initial.do: initial.f90
initial.o: kinds_mod.o
initial.o: blocks.o
initial.o: domain.o
initial.o: constants.o
initial.o: communicate.o
initial.o: broadcast.o
initial.o: prognostic.o
initial.o: solvers.o
initial.o: grid.o
initial.o: io.o
initial.o: io_types.o
initial.o: baroclinic.o
initial.o: barotropic.o
initial.o: pressure_grad.o
initial.o: surface_hgt.o
initial.o: vertical_mix.o
initial.o: horizontal_mix.o
initial.o: advection.o
initial.o: diagnostics.o
initial.o: state_mod.o
initial.o: time_management.o
initial.o: topostress.o
initial.o: ice.o
initial.o: xdisplay.o
initial.o: output.o
initial.o: tavg.o
initial.o: forcing.o
initial.o: forcing_coupled.o
initial.o: exit_mod.o
initial.o: restart.o
initial.o: global_reductions.o
initial.o: timers.o
